name: Pre-commit checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run pre-commit checks
        run: |
          nix develop --command pre-commit run --all-files
